language: cpp
compiler:
  - g++
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libgtest-dev
  - sudo apt-get install cmake 
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - sudo apt-get install libboost-graph-dev
  - sudo wget https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz
  - sudo tar zxvf glog-0.3.3.tar.gz
  - cd glog-0.3.3
  - ./configure
  - sudo make && make install
  - cd ${TRAVIS_BUILD_DIR} 
  - chmod +x init.sh 
  - ./init.sh 
script: 
  - make
  - make check
