language: cpp
compiler:
  - g++
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update
install:
  - sudo apt-get install -qq g++-4.8 libboost-graph-dev libgtest-dev cmake
  - export CXX="g++-4.8"
before_script:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - sudo wget https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz
  - sudo tar zxvf glog-0.3.3.tar.gz
  - cd glog-0.3.3
  - sudo ./configure
  - sudo make 
  - sudo make install
  - cd ..
  - sudo git clone https://github.com/sirikata/json-spirit.git
  - cd json-spirit; cd build; cmake .; make; sudo make install  
  - cd ${TRAVIS_BUILD_DIR} 
  - chmod +x init.sh 
  - ./init.sh 
script: 
  - make
  - make check
