language: cpp
compiler:
  - g++
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-4.8 libboost-all-dev libgtest-dev cmake
  - export CXX="g++-4.8"
  - sudo apt-get install -y gdb  # install gdb
before_script:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - sudo wget https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz
  - sudo tar zxvf glog-0.3.3.tar.gz
  - cd glog-0.3.3
  - sudo ./configure
  - sudo make 
  - sudo make install
  - cd ..
  - sudo git clone https://github.com/sirikata/json-spirit.git
  - cd json-spirit; cd build; sudo cmake .; sudo make; sudo make install  
  - cd ${TRAVIS_BUILD_DIR} 
  - chmod +x init.sh 
  - ./init.sh 
  - ulimit -c unlimited -S
script: 
  - make
  - make check
after_failure:
    - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
    - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
