language: cpp
compiler:
  - g++
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-4.8 libboost-graph-dev libgtest-dev cmake
  - export CXX="g++-4.8"
before_script:
  - sudo wget https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz
  - sudo tar zxvf glog-0.3.3.tar.gz
  - cd glog-0.3.3
  - sudo ./configure
  - sudo make 
  - sudo make install
  - cd ${TRAVIS_BUILD_DIR} 
  - chmod +x init.sh 
  - ./init.sh 
script: 
  - make
  - make check
